[package]
name = "node-cache"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
node-cache-recorder.workspace = true
node-cache-rpc.workspace = true

alloy-provider.workspace = true
clap.workspace = true
eyre.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
reth-rpc-api.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true
